config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index'
  resources :cocktails, only: [:index, :show, :new, :create, :destroy]  do
    resources :doses, only: [:index, :new, :create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  validates :name, uniqueness: true
  validates :name, presence: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail
  validates :description, :cocktail, :ingredient, presence: true
  validates :cocktail_id, :uniqueness => { :scope => :ingredient_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, uniqueness: true
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to root_path
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def index
    @cocktail = Cocktail.find(params[:cocktail_id])
    @doses = Dose.where(cocktail: @cocktail)
  end

  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail

    if @dose.save
      redirect_to cocktail_path(@dose.cocktail)
    else
      render 'cocktails/show'
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:ingredient_id, :cocktail_id, :description)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class=margine>
  <header class="banner">
    <div class="cocktail-logo">
      <%= image_tag "cocktail_2.png", alt: "logo", class:"logo" %>
    </div>

    <div class="text-box">
      <h1 class="heading-primary" >
        <span class="heading-primary-main"> Cocktail world</span>
        <span class="heading-primary-sub"> Create your own cocktails and become a master</span>
      </h1>
      <%= link_to new_cocktail_path, class:"btn btn-white-border" do %>
            <i class="fas fa-plus align-center"></i> Create a new cocktail
      <% end %>
    </div>
  </header>

  <div class="heading-primary-sub pink text-center">
    <h2>Explore our cocktails and add your touch</h2>
    <h2>with new ingredients</h2>
  </div>

  <div class="container d-flex">
    <% @cocktails.each do |cocktail| %>
      <% if cocktail.photo.url %>
        <%= link_to cocktail_path(cocktail) do %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path cocktail.photo, height: 300, width: 400, crop: :fill %>')">
            <%= cocktail.name %>
        <% end %>
            <%= link_to cocktail, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <i class="fas fa-trash homepage"></i>
            <% end %>
          </div>
      <% else %>
        <%= link_to cocktail_path(cocktail) do %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('https://images.pexels.com/photos/68672/beach-beverage-caribbean-cocktail-68672.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500')">
              <%= cocktail.name %>
              <% end %>
              <%= link_to cocktail, method: :delete, data: { confirm: 'Are you sure?' } do %>
                <i class="fas fa-trash homepage"></i>
              <% end %>
          </div>
      <% end %>
    <% end %>
</div>

app/views/cocktails/new.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <a class="navbar-brand" href="/">
    <%= image_tag "cocktail_2.png", alt: "logo", class:"logo" %>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Learn more about me</a>
      </li>
      <li class="nav-item dropdown">
        <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="" />
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Contact Lola</a>
        </div>
      </li>
    </ul>
  </div>
</div>

<div class="white-box">
 <div class="inner-white-box">
    <h2>Create</h2>
    <h2>a new cocktail</h2>
      <%= simple_form_for @cocktail do |f|%>
        <%= f.input :name %>
        <%= f.input :photo %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.submit "add a cocktail", class: "button-purple-border" %>
      <% end %>
   </div>
</div>

app/views/cocktails/show.html.erb
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <a class="navbar-brand" href="/">
      <%= image_tag "cocktail_2.png", alt: "logo", class:"logo" %>
  </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home</a>
        </li>
        <li class="nav-item dropdown">
          <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="" />
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Contact Lola</a>
          </div>
        </li>
      </ul>
    </div>
  </div>

  <div class="text-center">
    <h2 class=cocktail-title><%= @cocktail.name.capitalize %></h2>
     <div class= "d-flex justify-content-around align-items-center">
        <div class="pattern">

        </div>

         <% if @cocktail.photo.url %>
           <div class="cocktail-show" style="background-image: url('<%= cl_image_path @cocktail.photo, height: 450, width: 450, crop: :fill %>');">
         <% else %>
           <div class="cocktail-show" style="background-image: url('https://images.pexels.com/photos/68672/beach-beverage-caribbean-cocktail-68672.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500')">

         <% end %>


           </div>
          <div class="text-show">
            "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci ipsum rerum, modi corporis amet cupiditate debitis, numquam officiis eligendi, nostrum nulla doloremque culpa voluptate provident officia, pariatur nobis tempora! Laborum"
          </div>
      </div>
      <br>
      <br>
      <h5 class=text-center>Ingredients</h5>
      <div class=show-ingredients>
        <% @cocktail.doses.each do |dose| %>
                    <tr>
                      <td><%= dose.ingredient.name %></td>
                      <td><%= dose.description %></td>
                      <td>
                        <%= link_to dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } do %>
                          <i class="fas fa-times" style="color:purple;"></i>
                        <% end %>
      <% end %>
      </div>
     <!--  -->
    <br>
    <br>
    <br>
  </div>
    <div class="container mx-3">
      <br>
      <h3>Add an ingredient</h3>
        <%= simple_form_for [@cocktail, @dose] do |f|%>
        <%= f.input :description %>
        <%= f.association :ingredient %>
        <%= f.submit "Add an ingredient", class: "button-purple-border"%>
        <% end %>
        <br>
      <%= link_to "Back", root_path %>
    </div>

app/views/doses/index.html.erb
<h1>Doses</h1>
<% @doses.each do |dose| %>
<ul>
  <li><%= dose.ingredient.name %></li>
  <li><%= dose.description %></li>
  <%= link_to dose_path(dose), method: :delete, data: { confirm: 'Are you sure?' } do %>
  <i class="fas fa-trash"></i>
  <% end %>
</ul>
<% end %>

<%= link_to 'Back', cocktail_path(@cocktail)%>

app/views/doses/new.html.erb
<h1>Add an ingredient</h1>
<%= simple_form_for @dose do |f|%>
  <%= f.input :description %>
  <%= f.input :ingredient %>
  <%= f.submit "add an ingredient", class: "btn btn-primary" %>
<% end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag "application" %>    <!-- from app/javascript/packs/application.js -->
  </body>
</html>